---
title: "Professional Experience"
output: html_document
---

## National Cancer Institute
## Research
Postbaccalaureate Fellow 		
NCI Fellow 											Nov 2021 – Nov 2022
NIH Undergraduate Scholarship Program (UGSP) Scholar					Aug 2020 – Oct 2021
National Cancer Institute | Division of Cancer Epidemiology and Genetics | Clinical Genetics Branch 
Principal Investigators: Dr. Sharon Savage and Dr. Payal Khincha
Project 1: Hormone Receptor Status of Bilateral Breast Cancer in Individuals with Li-Fraumeni Syndrome
-	First authored a manuscript describing LFS Bilateral Breast Cancer and Hormone Receptors 
-	Collected data from multiple sources, confirmed hormone and cancer diagnosis,
and refined inclusion criteria for the study. 
-	Described in detail the hormone receptor status in LFS women with bilateral breast cancer. 
Project 2: Prevalence of autoimmune disease in Li-Fraumeni Syndrome 
-	First authored a Letter to the Editor of Familial Cancer Journal
-	Collected questionnaire data in collaboration with Westat and refined inclusion 
criteria for the study.  
-	Conducted statistical analysis of collected data.
-	Shared and presented results with cohort individuals and mentors at
an international conference.

## Clinical Shadowing
Pediatric Oncology Branch Student Shadowing Program (~2.5 hours per week)
National Cancer Institute | Division of Cancer Epidemiology and Genetics | Clinical Genetics Branch
	Learned about clinical trials and care provided by the Pediatric Oncology Branch (virtual). 	
LFS Patients, Genetic Counseling and Physician Sessions (5 sessions total)
National Cancer Institute | Division of Cancer Epidemiology and Genetics | Clinical Genetics Branch
Dr. Payal Khincha, Megan Frone, and Jessica Hatton
	Learned about LFS patient care provided by the LFS Physician and Genetic Counselors (virtual).


## Mathematical and Theoretical Biology Institute at Arizona State University

Principal Investigators: Drs. Aditi Ghosh, Christopher Kribs, Leon Arriola, and Bajoun Song 
Project: Minimization of drug-resistant gonorrhea cases through cost-effective treatment plans
-	Participated in several graduate-like statistical and computer programing classes.
-	Composed a novel study idea for mentor evaluations.
-	Compiled a literature review of current data of gonorrhea and transmission rate. 
-	Developed a novel SIS math model for predicating drug resistant cases of 
gonorrhea using R, MATLAB, Mathematica, and Maple.
